### ISSUE TITLE
What is instruction_per_seed_task in your experiment?

### ISSUE THREAD

**Issue by Tokgoleo** [SqueezeAILab/LLM2LLM#2]
It seems that instruction_per_seed_task is not reported in the **Experiment Setup** section of your paper? I find in your code that it's four by default.

**Comment by dragon18456** [comment]
For LLM2LLM, this value is 1. It is set here in the config: https://github.com/SqueezeAILab/LLM2LLM/blob/main/GSM8K/config.yaml#L8
You can use it to set the total number of augmentations per seed task.
