### ISSUE TITLE
where is step 6 from the readme

### ISSUE THREAD

**Issue by chiragshah285** [SqueezeAILab/LLM2LLM#3]
Readme says:
`6. cd into your experiment folder and run ./run_all.sh`

where is the experiments folder?

**Comment by dragon18456** [comment]
`generator_gsm.py` will generate an experiment folder based on the base_path in the config here: https://github.com/SqueezeAILab/LLM2LLM/blob/main/GSM8K/config.yaml#L4. In this case, for example, there will be a folder called `llama2_0.1_chatgpt_10steps_1example` which will have `run_all.sh` inside it.
