### ISSUE TITLE
where is run_all.sh

### ISSUE THREAD

**Issue by TTCoding** [SqueezeAILab/LLM2LLM#4]
Thank you for open-sourcing this work . I'd like to try it on my own dataset. But I cannot find the complete running pipeline 'run_all.sh'. Is it missing?

**Comment by dragon18456** [comment]
when you run `generator_gsm.py`, it will generate an experiment folder based on the base_path in the config here: https://github.com/SqueezeAILab/LLM2LLM/blob/main/GSM8K/config.yaml#L4. In this case, for example, there will be a folder called `llama2_0.1_chatgpt_10steps_1example` which will have `run_all.sh` inside it.
